[all]
exclude-files = [
    "crates/rules-uniffi/src/unneeded_when_moved_to_sargon.rs",
    "crates/rules-uniffi/src/error_conversion.rs",
]
verbose = false
force-clean = true
timeout = "2m"
locked = true
all-features = true
jobs = 1
out = ["Html"]
