# Testing CI - Runs on each PR and Push

name: Test
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: nightly-2024-01-11
  RUST_COMPONENTS: "rust-std"
jobs:
  # cargo fmt check
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: RDXWorks-actions/checkout@main

      - name: Install Rust Toolchain
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          default: true
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --check

  # clippy
  check-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: RDXWorks-actions/checkout@main

      - name: Install Rust Toolchain
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          default: true
          components: clippy

      - name: Clippy Check
        run: cargo clippy --all

  # Rust unit, doc and integration
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: RDXWorks-actions/checkout@main

      - name: Install Rust Toolchain
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          default: true

      - name: Run rust tests
        run: cargo test

  # Code Coverage uses Tarpaulin and uploads to CodeCov.io
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: RDXWorks-actions/checkout@main

      - uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
        with:
          role_name: 'arn:aws:iam::${{ secrets.SECRETS_ACCOUNT_ID }}:role/gh-common-secrets-read-access'
          app_name: 'sargon-mfa'
          step_name: 'sargon-mfa-code-cov-token'
          prefix: GH_CODECOV
          secret_name: 'arn:aws:secretsmanager:eu-west-2:${{ secrets.SECRETS_ACCOUNT_ID }}:secret:github-actions/common/codecov-o1ImFr'
          parse_json: true

      - name: Install Rust Toolchain
        uses: RDXWorks-actions/toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          default: true

      - name: Install cargo tarpaulin
        uses: RDXWorks-actions/cargo-install@main
        with:
          crate: cargo-tarpaulin
          tag: 0.30.0
          locked: true

      - name: Code Coverage - Generate
        run: cargo tarpaulin --out xml

      - name: Code Coverage - Upload to CodeCov.io
        uses: RDXWorks-actions/codecov-action@main
        with:
          token: ${{ env.GH_CODECOV_TOKEN }}
          fail_ci_if_error: true
